# Generated by Django 5.2.4 on 2026-03-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_result_total'),
        ('students', '0003_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_students', to='academics.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
