# Generated by Django 5.2.4 on 2026-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_parent_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
