# Generated by Django 5.2.4 on 2026-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parent_profiles/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
    ]
