# Generated by Django 5.2.4 on 2026-03-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_schooladmin_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Principal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="principals", to="core.school")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="principal_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ExamOfficer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exam_officers", to="core.school")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="exam_officer_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
