# Generated by Django 5.2.4 on 2026-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
